import { useEffect, useMemo, useState } from 'react';
import { MapContainer, TileLayer, Polygon, Marker, useMap, useMapEvents } from 'react-leaflet';
import L from 'leaflet';
import type { LatLngExpression } from 'leaflet';
import 'leaflet/dist/leaflet.css';
import { supabase } from '../lib/supabase';
import { RESTAURANT_ID } from '../lib/tenant';

type Zone = { id:string; name:string; delivery_fee:number; min_order_amount:number|null; is_active:boolean; boundary_geojson:any };
type Point = [number, number];
const cairo:Point=[30.0444,31.2357];
const input='mt-1 w-full rounded-lg border border-line bg-canvas px-3 py-2 text-sm outline-none focus:border-accent focus:ring-1 focus:ring-accent';
const pointIcon=L.divIcon({className:'zone-point-handle',html:'<span style="display:block;width:18px;height:18px;border-radius:9999px;background:var(--accent,#111827);border:3px solid white;box-shadow:0 1px 5px rgba(0,0,0,.35);cursor:grab"></span>',iconSize:[18,18],iconAnchor:[9,9]});

export default function DeliveryZones(){
 const [zones,setZones]=useState<Zone[]>([]),[loading,setLoading]=useState(true),[draft,setDraft]=useState<Zone|null>(null),[points,setPoints]=useState<Point[]>([]),[drawing,setDrawing]=useState(false),[message,setMessage]=useState<string|null>(null),[search,setSearch]=useState('');
 async function load(){setLoading(true);const r=await supabase.from('delivery_zones').select('id,name,delivery_fee,min_order_amount,is_active,boundary_geojson').eq('restaurant_id',RESTAURANT_ID).order('name');if(r.error)setMessage(r.error.message);setZones(r.data||[]);setLoading(false)}
 useEffect(()=>{load()},[]);
 const geo=useMemo(()=>points.length>=3?{type:'Polygon',coordinates:[[...points.map(([lat,lng])=>[lng,lat]),[points[0][1],points[0][0]]]]}:null,[points]);
 function openNew(){setDraft({id:'',name:'',delivery_fee:0,min_order_amount:0,is_active:true,boundary_geojson:null});setPoints([]);setDrawing(true);setMessage(null)}
 function edit(z:Zone){const ring=z.boundary_geojson?.coordinates?.[0]||[];const pts=ring.slice(0,-1).map((p:number[])=>[p[1],p[0]] as Point);setDraft({...z});setPoints(pts);setDrawing(false);setMessage(null)}
 async function save(){if(!draft?.name.trim()){setMessage('Zone name is required.');return}if(points.length<3){setMessage('Draw at least 3 points to create the zone boundary.');return}const payload={restaurant_id:RESTAURANT_ID,name:draft.name.trim(),delivery_fee:Number(draft.delivery_fee)||0,min_order_amount:Number(draft.min_order_amount)||0,is_active:draft.is_active,boundary_geojson:geo};const r=draft.id?await supabase.from('delivery_zones').update(payload).eq('id',draft.id):await supabase.from('delivery_zones').insert(payload);if(r.error){setMessage(r.error.message);return}setDraft(null);setPoints([]);setDrawing(false);setMessage('Delivery zone saved successfully.');load()}
 async function remove(id:string){if(!window.confirm('Delete this delivery zone?'))return;const r=await supabase.from('delivery_zones').delete().eq('id',id);if(r.error)setMessage(r.error.message);else load()}
 function startSearch(){const q=search.trim();if(!q){setMessage('Type an area, city, governorate, or landmark to search.');return}window.dispatchEvent(new CustomEvent('delivery-zone-map-search',{detail:q}))}
 return <div className="max-w-7xl p-8 pb-16"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="font-display text-2xl font-semibold">Delivery Zones</h1><p className="mt-1 text-sm text-ink/60">Search for an area, zoom to it, then draw a boundary. Hold and drag any point handle to move it precisely.</p></div><button onClick={openNew} className="rounded-lg bg-accent px-4 py-2 text-sm font-semibold text-white">Add Zone</button></header>{message&&<div className="mt-4 rounded-lg border border-line bg-surface px-4 py-3 text-sm">{message}</div>}
 <div className="mt-4 flex gap-2"><input value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')startSearch()}} placeholder="Search area, city, governorate or landmark…" className={input}/><button onClick={startSearch} className="shrink-0 rounded-lg bg-accent px-5 py-2 text-sm font-semibold text-white">Search</button></div>
 <div className="mt-4 grid gap-6 lg:grid-cols-[1fr_360px]"><div className="overflow-hidden rounded-2xl border border-line bg-surface"><MapContainer center={cairo as LatLngExpression} zoom={11} scrollWheelZoom className="h-[620px] w-full"><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><MapSearch/><MapClick drawing={drawing} onPoint={p=>setPoints(x=>[...x,p])}/>{points.length>=2&&<Polygon positions={points as LatLngExpression[]} pathOptions={{color:'var(--accent,#111827)',fillOpacity:.2}}/>}{points.map((p,i)=><DraggablePoint key={i} point={p} onMove={p=>setPoints(old=>old.map((x,n)=>n===i?p:x))}/>)}{zones.map(z=>{const ring=z.boundary_geojson?.coordinates?.[0]||[];if(ring.length<4)return null;return <Polygon key={z.id} positions={ring.slice(0,-1).map((p:number[])=>[p[1],p[0]]) as LatLngExpression[]} pathOptions={{fillOpacity:.08}}/>})}</MapContainer></div>
 <div className="rounded-2xl border border-line bg-surface p-5">{draft?<><div className="flex items-center justify-between"><h2 className="font-display text-lg font-semibold">{draft.id?'Edit Zone':'New Zone'}</h2><button onClick={()=>{setDraft(null);setDrawing(false)}} className="text-ink/40">✕</button></div><label className="mt-5 block text-xs font-medium uppercase tracking-wide text-ink/50">Zone Name</label><input className={input} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/><label className="mt-4 block text-xs font-medium uppercase tracking-wide text-ink/50">Delivery Fee</label><input type="number" min="0" step="0.01" className={input} value={draft.delivery_fee} onChange={e=>setDraft({...draft,delivery_fee:Number(e.target.value)})}/><label className="mt-4 block text-xs font-medium uppercase tracking-wide text-ink/50">Minimum Order</label><input type="number" min="0" step="0.01" className={input} value={draft.min_order_amount??0} onChange={e=>setDraft({...draft,min_order_amount:Number(e.target.value)})}/><label className="mt-4 flex items-center justify-between rounded-lg border border-line bg-canvas px-3 py-2 text-sm"><span>Active</span><input type="checkbox" checked={draft.is_active} onChange={e=>setDraft({...draft,is_active:e.target.checked})}/></label><div className="mt-5 rounded-lg border border-line bg-canvas p-3 text-xs text-ink/60"><strong className="text-ink">Boundary:</strong> {points.length} points. {drawing?'Click the map to add points. After placing a point, hold its handle and drag it.':'Hold and drag any point handle to reposition it.'}</div><div className="mt-4 flex gap-2"><button onClick={()=>{setPoints([]);setDrawing(true)}} className="rounded-lg border border-line px-3 py-2 text-sm">Clear & Redraw</button><button onClick={save} className="flex-1 rounded-lg bg-accent px-3 py-2 text-sm font-semibold text-white">Save Zone</button></div></>:<><h2 className="font-display text-lg font-semibold">Your Zones</h2><p className="mt-1 text-sm text-ink/50">{zones.length} zone{zones.length===1?'':'s'} configured.</p><div className="mt-5 space-y-3">{loading?<p className="text-sm text-ink/50">Loading…</p>:zones.length===0?<p className="text-sm text-ink/50">No zones yet. Click Add Zone and draw a polygon.</p>:zones.map(z=><div key={z.id} className="rounded-xl border border-line bg-canvas p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{z.name}</p><p className="mt-1 text-xs text-ink/50">Fee: {z.delivery_fee} · Min: {z.min_order_amount??0} · {z.is_active?'Active':'Inactive'}</p></div><span className="text-xs">{z.boundary_geojson?.type==='Polygon'?'Polygon':'No boundary'}</span></div><div className="mt-3 flex gap-3"><button onClick={()=>edit(z)} className="text-sm font-medium text-accent">Edit</button><button onClick={()=>remove(z.id)} className="text-sm font-medium text-danger">Delete</button></div></div>)}</div></>}</div></div></div>
}
function MapClick({drawing,onPoint}:{drawing:boolean;onPoint:(p:Point)=>void}){useMapEvents({click:e=>{if(drawing)onPoint([e.latlng.lat,e.latlng.lng])}});return null}
function MapSearch(){const map=useMap();useEffect(()=>{const handler=(e:Event)=>{const q=(e as CustomEvent<string>).detail;fetch(`https://nominatim.openstreetmap.org/search?format=jsonv2&limit=1&q=${encodeURIComponent(q)}`,{headers:{Accept:'application/json'}}).then(r=>r.json()).then((data:any[])=>{if(!data.length){window.alert('Location not found. Try a more specific area name.');return}const x=data[0];map.flyTo([Number(x.lat),Number(x.lon)],14,{duration:1.2})}).catch(()=>window.alert('Could not search the map right now.'))};window.addEventListener('delivery-zone-map-search',handler);return()=>window.removeEventListener('delivery-zone-map-search',handler)},[map]);return null}
function DraggablePoint({point,onMove}:{point:Point;onMove:(p:Point)=>void}){return <Marker position={point as LatLngExpression} icon={pointIcon} draggable eventHandlers={{drag:(e)=>{const marker=e.target as L.Marker;const ll=marker.getLatLng();onMove([ll.lat,ll.lng])}}}/>}
